### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prepend' of null

### ISSUE THREAD

**Issue by AlifBrahim** [Prabhav-R/bookGrab-chrome-extension#2]
Hi Prabhav-R,
I had unpacked the extension and couldn't get the extension running. I got the error, " Uncaught TypeError: Cannot read property 'prepend' of null ". The following are the details:

Context:
https://www.amazon.com/gp/bestsellers/books/4736/ref=s9_acsd_obs_hd_bw_b1EO_clnk/ref=s9_acsd_obs_hd_bw_b1EO_c2_x_c2cl?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-11&pf_rd_r=CPM50KDBAYHMZZ67MZQ0&pf_rd_t=101&pf_rd_p=7f883d3e-ac3e-5bec-8f9d-771bc379b38a&pf_rd_i=4736

Stack Trace:
contentScript.js:32 (anonymous function)

const openNewTab = (fetchBookName) => {
  const dest = fetchBookName();

  chrome.runtime.sendMessage({ action: "open_new_tab", url: dest }, (r) => {});
};

const createButton = () => {
  const btn = document.createElement("button");
  btn.textContent = "Search For PDF";
  btn.style.padding = ".9rem";
  btn.style.backgroundColor = "#337ab7";
  btn.style.borderRadius = ".1rem";
  btn.style.color = "white";
  btn.style.border = ".1rem solid #337ab7";
  // btn.style.fontSize = "1rem";

  return btn;
};

const amazon_addbtn = (fetchBookName) => {
  if (
    document
      .querySelector("#nav-global-location-data-modal-action")
      .attributes[2].value.search("books") !== -1
  ) {
    const ul = document.querySelector(
      "ul.a-unordered-list.a-nostyle.a-button-list.a-horizontal"
    );

    const btn = createButton();
    btn.addEventListener("click", () => openNewTab(fetchBookName));
    ul.prepend(btn);
  }
};

const amazon_bookname = () => {
  const bookName = document.querySelector("#productTitle").textContent.trim();

  const dest = "https://1lib.in/s/" + encodeURI(bookName);

  return dest;
};

const goodreads_addbtn = (fetchBookName) => {
  const ul = document.querySelector("ul.buyButtonBar.left");
  if (ul) {
    const btn = createButton();
    btn.addEventListener("click", () => openNewTab(fetchBookName));
    ul.prepend(btn);
  }
};

const goodreads_bookname = () => {
  const bookName = document.querySelector("#bookTitle").textContent.trim();
  const dest = "https://1lib.in/s/" + encodeURI(bookName);
  return dest;
};

const init = () => {
  const host = window.location.hostname.split(".")[1];

  switch (host) {
    case "goodreads":
      return [goodreads_addbtn, goodreads_bookname];
    case "amazon":
      return [amazon_addbtn, amazon_bookname];
  }
  return [null, null];
};

(() => {
  const [addButton, fetchBookName] = init();

  if (addButton && fetchBookName) {
    addButton(fetchBookName);
  }
})();

Could you solve the issue?

**Comment by Prabhav-R** [comment]
Hi @ScientistAlif,

First of all, thank you for trying about the extension. I would like to remind you that the extension adds a button onto the page only when you visit the product page. 

I have looked into the issue you raised and I found out that the extension was not adding the button for products from the product listing page you provided. Thank you for reporting this. I have fixed it and have added the feature to use the extension in amazon audible and the ebook's product page as well.

**AUDIBLE PRODUCT PAGE**
<img width="1339" alt="amz_audible_page" src="https://user-images.githubusercontent.com/45042455/123423242-ec5d7000-d5dc-11eb-981e-52362414fc2a.png">

**EBOOKS PRODUCT PAGE**
<img width="1144" alt="amz_ebook_page" src="https://user-images.githubusercontent.com/45042455/123423321-0b5c0200-d5dd-11eb-8b88-ad868e16032b.png">



Please try it out and see if the issue has been resolved :)

**Comment by AlifBrahim** [comment]
No, it still didn't show on the product page. I went to this site, [https://www.amazon.com/Subtle-Art-Not-Giving-Counterintuitive/dp/0062457713] , and the button didn't show on the page. However, it worked on Goodreads. Only Amazon had the issue.

**Comment by Prabhav-R** [comment]
@ScientistAlif  I checked the page u mentioned, it is working for me. Did you pull the updated code from the repo? Or maybe it might be some browser issue I guess. I'm using Chrome Version 91.0.4472.114.

<img width="994" alt="demo" src="https://user-images.githubusercontent.com/45042455/123514329-1df33b80-d6b0-11eb-8f19-a2810f975119.png">

**Comment by AlifBrahim** [comment]
I just updated the repo. It works now. Thank you Prabhav-R for making this extension. It's easier for people to search Amazon books with just a click of a button into Z-Library without copy paste.

**Comment by Prabhav-R** [comment]
@ScientistAlif Thank you for trying it out 😁. I shall close the issue now.
